inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-dbl:
    - config/dbl.yml

AllCops:
  TargetRubyVersion: 3.2

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Style/IfUnlessModifier:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Naming/PredicateName:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/ParameterLists:
  Max: 8
